### ISSUE TITLE
branch idf3: 2nd esp_mqtt_publish(QOS1) always fails

### ISSUE THREAD

**Issue by pantaluna** [256dpi/esp-mqtt#15]
The latest version fails consistently during the second mqtt publish request when using QOS1. Note that QOS0 works fine.

The error message is "esp_mqtt: lwmqtt_yield: -4"

Please test with this project https://github.com/pantaluna/support_esp_mqtt

Thanks.

**Comment by 256dpi** [comment]
What broker are you using?

I tested the included example in this repository successfully with shiftr.io and mosquitto in all QoS modes.

BTW: Since you use the master branch of esp-idf: I just published a "idf3" branch with the necessary changes to work with esp-idf v3.

**Comment by pantaluna** [comment]
Thanks for the follow-up.
I have re-tested it with the "idf3" branch of esp_mqtt towards your broker.shiftr.io mqtt server, and against a local Mosquitto mqqt server. The problem remains the same.

**Comment by 256dpi** [comment]
@pantaluna @vortex314 I found the issue. There was an issue with the background process task interfering with the publish method. This caused them to do work the other task was supposed to do and thus yield an error. Somehow, this only triggered if messages are published from `app_main` or a task with priority 1 (the lowest possible). Anyway, I tested @pantaluna's code with the fix and the issue should be resolved now. This should also fix some potential delays when using QoS > 0.

I released a new version for IDF 2.1.1. and rebased the idf3 branch. Please test your code again and give me some feedback if this has been resolved fully. 🚀

**Comment by pantaluna** [comment]
It works. Thanks!

**Comment by 256dpi** [comment]
Awesome!
